require 'rake'
require 'yaml'
require 'erb'
require_relative './lib/metrics_helper'
require 'set'
require 'json'

def deep_merge(a, b)

  # Loop over key/value pairs
  b.each { |key, value|

    # If key from B present in map A
    if a.key? key

      # If both are hashes call recursively
      if (a[key].class == Hash and b[key].class == Hash)
        a[key] = deep_merge(a[key], value)
      else
        # Overwrite value with value from B
        a[key] = value
      end
    else
      # Add key from B
      a[key] = value
    end
  }

  # Return hash a
  return a
end

def get_metrics_configuration(ciinabox_metrics_root)
  metrics_configuration = {}
  # Read configuration
  Dir.glob("#{ciinabox_metrics_root}/conf/*.yml") do |yamlConf|
    tmp_configuration = YAML.load_file(yamlConf)
    metrics_configuration = deep_merge(metrics_configuration, tmp_configuration)
  end
  metrics_configuration
end

namespace :ciinabox do

  ciinabox_metrics_root = ENV['CIINABOX_METRICS_ROOT'] || '/etc/ciinabox-metrics'
  ciinabox_metrics_runtime = ENV['CIINABOX_METRICS_RUNTIME'] || `echo $PWD|xargs echo -n`
  ciinabox_metrics_user = ENV['CIINABOX_METRICS_USER'] || `echo $USER|xargs echo -n`
  instance_info_file_path = "#{ciinabox_metrics_root}/instance_info.json"

  default_conf = {
      'dimensions' => {'asg' => false, 'availability_zone' => false, 'instance' => true}
  }

  if not File.directory?(ciinabox_metrics_runtime)
    STDERR.puts("Runtime directory #{ciinabox_metrics_runtime} not found. ")
    exit -3
  end

  if not File.directory?(ciinabox_metrics_root)
    STDERR.puts("Configuration directory #{ciinabox_metrics_root} not found. Use CIINABOX_METRICS_ROOT to set different directory ")
    exit -3
  end

  ENV['CIINABOX_METRICS_SCRIPTS'] = ciinabox_metrics_root + '/scripts'

  desc("Install metric cron jobs")
  task :install_metrics_cron => [:save_instance_info] do
    metrics_configuration = get_metrics_configuration(ciinabox_metrics_root)
    schedule_template = IO.read('./config/schedule.template.erb')
    template = ERB.new(schedule_template)
    compiled_template = template.result(OpenStruct.new({'frequencies' =>
                                                            metrics_configuration['metrics'].collect { |k, m| m['frequency'] }.to_set})
                                            .instance_eval { binding })

    IO.write('./config/schedule.rb', compiled_template)

    cron_preview = `whenever`
    system("whenever --update-crontab")

    puts("Updated user #{ciinabox_metrics_user} crontab with following schedule\n")
    puts("#{cron_preview}")
  end

  desc("Process single cron dsl expression")
  task :process_metric_cron, [:cron_dsl] do |t, args|
    instance_info = JSON.parse(File.read(instance_info_file_path))
    metrics_helper = MetricsHelper.new(instance_info)

    metrics_configuration = get_metrics_configuration(ciinabox_metrics_root)

    # Find all metrics matching given cron
    all_cron_metrics = metrics_configuration['metrics'].find_all { |key, conf|
      conf['frequency'] == args['cron_dsl']
    }

    # Build metric object and process metric for each of matched configurations
    all_cron_metrics.each do |key, val|
      metric_configuration = default_conf
      if (metrics_configuration['default'])
        metric_configuration = metric_configuration.merge(metrics_configuration['default'])
      end
      metric_configuration = metric_configuration.merge(val)
      metrics_helper.process_metric(metric_configuration,instance_info)
    end

    metrics_helper.flush_metrics()

  end

  desc("Read instance information and write to file")
  task :save_instance_info do
    write_instance_info(instance_info_file_path)
  end

end
